// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsj50LDJQJSVUr1iBMXiZxxJxZzDYWIyg',
    appId: '1:939453696359:web:ca8fa8bb988e09703dc7c2',
    messagingSenderId: '939453696359',
    projectId: 'tubitak-86d68',
    authDomain: 'tubitak-86d68.firebaseapp.com',
    storageBucket: 'tubitak-86d68.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoF6SfhhBH2LCRNopmdBOM2FwSdwcPQ7Y',
    appId: '1:939453696359:android:8f1b92eafbfdbe6e3dc7c2',
    messagingSenderId: '939453696359',
    projectId: 'tubitak-86d68',
    storageBucket: 'tubitak-86d68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7D0Wkq2YFvviAkfBVhm07Bi9QbLa6984',
    appId: '1:939453696359:ios:3fb7a7da7e2b1be63dc7c2',
    messagingSenderId: '939453696359',
    projectId: 'tubitak-86d68',
    storageBucket: 'tubitak-86d68.firebasestorage.app',
    iosBundleId: 'com.tubitak.tubitak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7D0Wkq2YFvviAkfBVhm07Bi9QbLa6984',
    appId: '1:939453696359:ios:3fb7a7da7e2b1be63dc7c2',
    messagingSenderId: '939453696359',
    projectId: 'tubitak-86d68',
    storageBucket: 'tubitak-86d68.firebasestorage.app',
    iosBundleId: 'com.tubitak.tubitak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsj50LDJQJSVUr1iBMXiZxxJxZzDYWIyg',
    appId: '1:939453696359:web:bef1426b5b11d24c3dc7c2',
    messagingSenderId: '939453696359',
    projectId: 'tubitak-86d68',
    authDomain: 'tubitak-86d68.firebaseapp.com',
    storageBucket: 'tubitak-86d68.firebasestorage.app',
  );
}
